# -----------------------------------------------------------------------------
# This file was copied from the Godot C++ repository:
# https://github.com/godotengine/godot-cpp
#
# Original author(s): Godot Engine contributors
# License: MIT License
# Full license text included below:
# You can also view the original license here:
# https://github.com/godotengine/godot-cpp/blob/master/LICENSE.md
#
# MIT License
# Copyright (c) 2017-present Godot Engine contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# -----------------------------------------------------------------------------

name: Setup godot-cpp
description: Setup build dependencies for godot-cpp.

inputs:
  platform:
    required: true
    description: Target platform.
  em-version:
    default: 4.0.11
    description: Emscripten version.
  windows-compiler:
    required: true
    description: The compiler toolchain to use on Windows ('mingw' or 'msvc').
    type: choice
    options:
      - mingw
      - msvc
    default: mingw
  mingw-version:
    default: 12.2.0
    description: MinGW version.
  ndk-version:
    default: r28b
    description: Android NDK version.
  buildtool:
    default: scons
    description: scons or cmake
  scons-version:
    default: 4.4.0
    description: SCons version.


runs:
  using: composite
  steps:
    - name: Setup Python (for SCons)
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Setup Android dependencies
      if: inputs.platform == 'android'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ inputs.ndk-version }}
        link-to-sdk: true

    - name: Setup Web dependencies
      if: inputs.platform == 'web'
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.em-version }}
        no-cache: true

    - name: Setup MinGW for Windows/MinGW build
      if: inputs.platform == 'windows' && inputs.windows-compiler == 'mingw'
      uses: egor-tensin/setup-mingw@v2
      with:
        version: ${{ inputs.mingw-version }}

    - name: Setup SCons
      if: ${{ inputs.buildtool == 'scons' }}
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons==${{ inputs.scons-version }}
        scons --version

    - name: Install Ninja
      if: ${{ inputs.buildtool == 'cmake' }}
      uses: ashutoshvarma/setup-ninja@master
